services:
  back:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: server-dev
    image: server-dev
    restart: always
    ports:
      - 8080:8080
    environment:
      - SPRING_PROFILES_ACTIVE=${PROFILE}
    networks:
      - kuis

networks:
  kuis:
    driver: bridge